[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", git = "https://github.com/ProChain/substrate.git" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/ProChain/substrate.git" }
substrate-executor = { git = "https://github.com/ProChain/substrate.git" }
primitives = { package = "substrate-primitives", git = "https://github.com/ProChain/substrate.git" }
trie = { package = "substrate-trie", git = "https://github.com/ProChain/substrate.git" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
node-testing = { path = "../testing" }
test-client = { package = "substrate-test-client", path = "../../../test/utils/client" }
sr-primitives = { git = "https://github.com/ProChain/substrate.git" }
runtime_support = { package = "frame-support", git = "https://github.com/ProChain/substrate.git" }
balances = { package = "pallet-balances", git = "https://github.com/ProChain/substrate.git" }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/ProChain/substrate.git" }
session = { package = "pallet-session", git = "https://github.com/ProChain/substrate.git" }
system = { package = "frame-system", git = "https://github.com/ProChain/substrate.git" }
timestamp = { package = "pallet-timestamp", git = "https://github.com/ProChain/substrate.git" }
treasury = { package = "pallet-treasury", git = "https://github.com/ProChain/substrate.git" }
contracts = { package = "pallet-contracts", git = "https://github.com/ProChain/substrate.git" }
grandpa = { package = "pallet-grandpa", git = "https://github.com/ProChain/substrate.git" }
indices = { package = "pallet-indices", git = "https://github.com/ProChain/substrate.git" }
wabt = "0.9.2"
criterion = "0.3.0"

[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
wasmi-errno = [
	"substrate-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false

